(define (problem catering-17)
    (:domain catering)
    (:objects Ramen Gazpacho Risotto_de_Pescado Canelones_de_Carne Fideua_con_Sepia Pastel_de_Pan Macarrones_Bolonesa Spaghettis_Bolonesa Huevos_Rellenos Crema_Calabacin Potaje_de_Alubias Paella Cuscus Tagliatelle_Bolonesa Escudella Ensalada_de_Col Patatas_Caliu - primero
              Rape_al_Limon Suquet_de_Pescado Bacalao Lasana_de_Atun Berenjas_al_Horno Salmon_Ahumado Fingers_de_Pollo Calamares_a_la_Romana Tortilla_de_Espinacas Albondigas Sopa_de_Miso Calsotada Raviolli Falafel Crema_Zanahoria Milanesa_Napolitana Costillas_de_Cerdo - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Ramen Sopa)
       (es_tipo Gazpacho Sopa)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Paella Pescado)
       (es_tipo Cuscus Vegetal)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Escudella Sopa)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Bacalao Pescado)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Albondigas Carne)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Calsotada Vegetal)
       (es_tipo Raviolli Pasta)
       (es_tipo Falafel Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Costillas_de_Cerdo Carne)
       (incompatible Risotto_de_Pescado Lasana_de_Atun)
       (incompatible Gazpacho Fingers_de_Pollo)
       (incompatible Macarrones_Bolonesa Sopa_de_Miso)
       (incompatible Ensalada_de_Col Raviolli)
       (incompatible Potaje_de_Alubias Calsotada)
       (incompatible Canelones_de_Carne Berenjas_al_Horno)
       (incompatible Huevos_Rellenos Salmon_Ahumado)
       (incompatible Paella Tortilla_de_Espinacas)
       (incompatible Spaghettis_Bolonesa Albondigas)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
)