(define (problem catering-16)
    (:domain catering)
    (:objects Spaghettis_Bolonesa Pastel_de_Pan Macarrones_Bolonesa Fideua_con_Sepia Croquetas Crema_Calabacin Huevos_Rellenos Gazpacho Judias_Verdes Patatas_Caliu Ensalada_de_Col Cuscus Tagliatelle_Bolonesa Paella Escudella Ramen - primero
              Sopa_de_Miso Suquet_de_Pescado Merluza_a_Naranja Milanesa_Napolitana Rape_al_Limon Salmon_Ahumado Berenjas_al_Horno Canelones_de_Pollo Tortilla_de_Espinacas Lasana_de_Atun Costillas_de_Cerdo Falafel Bacalao Albondigas Calamares_a_la_Romana Calsotada - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Croquetas Carne)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Gazpacho Sopa)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Cuscus Vegetal)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Paella Pescado)
       (es_tipo Escudella Sopa)
       (es_tipo Ramen Sopa)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Falafel Carne)
       (es_tipo Bacalao Pescado)
       (es_tipo Albondigas Carne)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Calsotada Vegetal)
       (incompatible Macarrones_Bolonesa Canelones_de_Pollo)
       (incompatible Cuscus Tortilla_de_Espinacas)
       (incompatible Patatas_Caliu Bacalao)
       (incompatible Pastel_de_Pan Sopa_de_Miso)
       (incompatible Ensalada_de_Col Lasana_de_Atun)
       (incompatible Huevos_Rellenos Costillas_de_Cerdo)
       (incompatible Gazpacho Salmon_Ahumado)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
)