(define (problem catering-16)
    (:domain catering)
    (:objects Risotto_de_Pescado Judias_Verdes Huevos_Rellenos Paella Potaje_de_Alubias Fideua_con_Sepia Gazpacho Patatas_Caliu Sushi Escudella Canelones_de_Carne Pastel_de_Pan Spaghettis_Bolonesa Cuscus Ensalada_de_Col Macarrones_Bolonesa - primero
              Canelones_de_Pollo Albondigas Falafel Berenjas_al_Horno Rape_al_Limon Merluza_a_Naranja Bacalao Tortilla_de_Espinacas Lasana_de_Atun Milanesa_Napolitana Crema_Zanahoria Sopa_de_Miso Suquet_de_Pescado Pastel_de_Verduras Salmon_Ahumado Fingers_de_Pollo - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Paella Pescado)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Gazpacho Sopa)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Sushi Pescado)
       (es_tipo Escudella Sopa)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Cuscus Vegetal)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Albondigas Carne)
       (es_tipo Falafel Carne)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Bacalao Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Fingers_de_Pollo Carne)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
)