(define (problem catering-18platos-9incmpls)
    (:domain catering)
    (:objects Ensalada_de_Col Ramen Potaje_de_Alubias Escudella Canelones_de_Carne Patatas_Caliu Risotto_de_Pescado Paella Macarrones_Bolonesa Spaghettis_Bolonesa Judias_Verdes Cuscus Tagliatelle_Bolonesa Croquetas Crema_Calabacin Fideua_con_Sepia Pastel_de_Pan Sushi - primero
              Costillas_de_Cerdo Calamares_a_la_Romana Canelones_de_Pollo Sopa_de_Miso Merluza_a_Naranja Calsotada Milanesa_Napolitana Salmon_Ahumado Bacalao Pastel_de_Verduras Fingers_de_Pollo Suquet_de_Pescado Lasana_de_Atun Tortilla_de_Espinacas Crema_Zanahoria Albondigas Rape_al_Limon Raviolli - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Ramen Sopa)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Escudella Sopa)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Paella Pescado)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Cuscus Vegetal)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Croquetas Carne)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Sushi Pescado)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Calsotada Vegetal)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Bacalao Pescado)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Albondigas Carne)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Raviolli Pasta)
       (incompatible Judias_Verdes Calamares_a_la_Romana)
       (incompatible Sushi Canelones_de_Pollo)
       (incompatible Fideua_con_Sepia Lasana_de_Atun)
       (incompatible Crema_Calabacin Tortilla_de_Espinacas)
       (incompatible Canelones_de_Carne Bacalao)
       (incompatible Risotto_de_Pescado Pastel_de_Verduras)
       (incompatible Potaje_de_Alubias Merluza_a_Naranja)
       (incompatible Macarrones_Bolonesa Costillas_de_Cerdo)
       (incompatible Ensalada_de_Col Milanesa_Napolitana)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Ensalada_de_Col) 6)
       (= (cals-plato Ensalada_de_Col) 270)
       (= (precio-plato Ramen) 7)
       (= (cals-plato Ramen) 731)
       (= (precio-plato Potaje_de_Alubias) 6)
       (= (cals-plato Potaje_de_Alubias) 276)
       (= (precio-plato Escudella) 8)
       (= (cals-plato Escudella) 725)
       (= (precio-plato Canelones_de_Carne) 8)
       (= (cals-plato Canelones_de_Carne) 533)
       (= (precio-plato Patatas_Caliu) 9)
       (= (cals-plato Patatas_Caliu) 341)
       (= (precio-plato Risotto_de_Pescado) 7)
       (= (cals-plato Risotto_de_Pescado) 343)
       (= (precio-plato Paella) 9)
       (= (cals-plato Paella) 354)
       (= (precio-plato Macarrones_Bolonesa) 7)
       (= (cals-plato Macarrones_Bolonesa) 417)
       (= (precio-plato Spaghettis_Bolonesa) 5)
       (= (cals-plato Spaghettis_Bolonesa) 572)
       (= (precio-plato Judias_Verdes) 9)
       (= (cals-plato Judias_Verdes) 560)
       (= (precio-plato Cuscus) 6)
       (= (cals-plato Cuscus) 548)
       (= (precio-plato Tagliatelle_Bolonesa) 9)
       (= (cals-plato Tagliatelle_Bolonesa) 690)
       (= (precio-plato Croquetas) 7)
       (= (cals-plato Croquetas) 260)
       (= (precio-plato Crema_Calabacin) 8)
       (= (cals-plato Crema_Calabacin) 331)
       (= (precio-plato Fideua_con_Sepia) 9)
       (= (cals-plato Fideua_con_Sepia) 365)
       (= (precio-plato Pastel_de_Pan) 5)
       (= (cals-plato Pastel_de_Pan) 739)
       (= (precio-plato Sushi) 8)
       (= (cals-plato Sushi) 382)
       (= (precio-plato Costillas_de_Cerdo) 8)
       (= (cals-plato Costillas_de_Cerdo) 805)
       (= (precio-plato Calamares_a_la_Romana) 9)
       (= (cals-plato Calamares_a_la_Romana) 800)
       (= (precio-plato Canelones_de_Pollo) 11)
       (= (cals-plato Canelones_de_Pollo) 498)
       (= (precio-plato Sopa_de_Miso) 8)
       (= (cals-plato Sopa_de_Miso) 704)
       (= (precio-plato Merluza_a_Naranja) 10)
       (= (cals-plato Merluza_a_Naranja) 407)
       (= (precio-plato Calsotada) 11)
       (= (cals-plato Calsotada) 650)
       (= (precio-plato Milanesa_Napolitana) 10)
       (= (cals-plato Milanesa_Napolitana) 450)
       (= (precio-plato Salmon_Ahumado) 9)
       (= (cals-plato Salmon_Ahumado) 829)
       (= (precio-plato Bacalao) 11)
       (= (cals-plato Bacalao) 672)
       (= (precio-plato Pastel_de_Verduras) 8)
       (= (cals-plato Pastel_de_Verduras) 837)
       (= (precio-plato Fingers_de_Pollo) 14)
       (= (cals-plato Fingers_de_Pollo) 492)
       (= (precio-plato Suquet_de_Pescado) 8)
       (= (cals-plato Suquet_de_Pescado) 676)
       (= (precio-plato Lasana_de_Atun) 13)
       (= (cals-plato Lasana_de_Atun) 836)
       (= (precio-plato Tortilla_de_Espinacas) 13)
       (= (cals-plato Tortilla_de_Espinacas) 648)
       (= (precio-plato Crema_Zanahoria) 12)
       (= (cals-plato Crema_Zanahoria) 687)
       (= (precio-plato Albondigas) 13)
       (= (cals-plato Albondigas) 480)
       (= (precio-plato Rape_al_Limon) 9)
       (= (cals-plato Rape_al_Limon) 708)
       (= (precio-plato Raviolli) 13)
       (= (cals-plato Raviolli) 538)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
