(define (problem catering-15platos-4incmpls)
    (:domain catering)
    (:objects Canelones_de_Carne Macarrones_Bolonesa Croquetas Pastel_de_Pan Ramen Escudella Fideua_con_Sepia Patatas_Caliu Paella Potaje_de_Alubias Sushi Tagliatelle_Bolonesa Crema_Calabacin Cuscus Risotto_de_Pescado - primero
              Calamares_a_la_Romana Pastel_de_Verduras Berenjas_al_Horno Costillas_de_Cerdo Bacalao Raviolli Falafel Calsotada Crema_Zanahoria Milanesa_Napolitana Albondigas Lasana_de_Atun Merluza_a_Naranja Tortilla_de_Espinacas Rape_al_Limon - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Croquetas Carne)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Ramen Sopa)
       (es_tipo Escudella Sopa)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Paella Pescado)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Sushi Pescado)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Cuscus Vegetal)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Bacalao Pescado)
       (es_tipo Raviolli Pasta)
       (es_tipo Falafel Carne)
       (es_tipo Calsotada Vegetal)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Albondigas Carne)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Rape_al_Limon Pescado)
       (incompatible Risotto_de_Pescado Rape_al_Limon)
       (incompatible Ramen Lasana_de_Atun)
       (incompatible Croquetas Milanesa_Napolitana)
       (incompatible Potaje_de_Alubias Bacalao)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Canelones_de_Carne) 8)
       (= (cals-plato Canelones_de_Carne) 274)
       (= (precio-plato Macarrones_Bolonesa) 7)
       (= (cals-plato Macarrones_Bolonesa) 537)
       (= (precio-plato Croquetas) 6)
       (= (cals-plato Croquetas) 400)
       (= (precio-plato Pastel_de_Pan) 8)
       (= (cals-plato Pastel_de_Pan) 578)
       (= (precio-plato Ramen) 5)
       (= (cals-plato Ramen) 493)
       (= (precio-plato Escudella) 9)
       (= (cals-plato Escudella) 573)
       (= (precio-plato Fideua_con_Sepia) 6)
       (= (cals-plato Fideua_con_Sepia) 507)
       (= (precio-plato Patatas_Caliu) 7)
       (= (cals-plato Patatas_Caliu) 358)
       (= (precio-plato Paella) 7)
       (= (cals-plato Paella) 727)
       (= (precio-plato Potaje_de_Alubias) 5)
       (= (cals-plato Potaje_de_Alubias) 495)
       (= (precio-plato Sushi) 7)
       (= (cals-plato Sushi) 427)
       (= (precio-plato Tagliatelle_Bolonesa) 8)
       (= (cals-plato Tagliatelle_Bolonesa) 392)
       (= (precio-plato Crema_Calabacin) 5)
       (= (cals-plato Crema_Calabacin) 661)
       (= (precio-plato Cuscus) 9)
       (= (cals-plato Cuscus) 402)
       (= (precio-plato Risotto_de_Pescado) 6)
       (= (cals-plato Risotto_de_Pescado) 675)
       (= (precio-plato Calamares_a_la_Romana) 13)
       (= (cals-plato Calamares_a_la_Romana) 613)
       (= (precio-plato Pastel_de_Verduras) 14)
       (= (cals-plato Pastel_de_Verduras) 811)
       (= (precio-plato Berenjas_al_Horno) 11)
       (= (cals-plato Berenjas_al_Horno) 546)
       (= (precio-plato Costillas_de_Cerdo) 8)
       (= (cals-plato Costillas_de_Cerdo) 693)
       (= (precio-plato Bacalao) 14)
       (= (cals-plato Bacalao) 886)
       (= (precio-plato Raviolli) 12)
       (= (cals-plato Raviolli) 687)
       (= (precio-plato Falafel) 11)
       (= (cals-plato Falafel) 847)
       (= (precio-plato Calsotada) 12)
       (= (cals-plato Calsotada) 761)
       (= (precio-plato Crema_Zanahoria) 8)
       (= (cals-plato Crema_Zanahoria) 807)
       (= (precio-plato Milanesa_Napolitana) 9)
       (= (cals-plato Milanesa_Napolitana) 897)
       (= (precio-plato Albondigas) 14)
       (= (cals-plato Albondigas) 594)
       (= (precio-plato Lasana_de_Atun) 12)
       (= (cals-plato Lasana_de_Atun) 629)
       (= (precio-plato Merluza_a_Naranja) 13)
       (= (cals-plato Merluza_a_Naranja) 692)
       (= (precio-plato Tortilla_de_Espinacas) 12)
       (= (cals-plato Tortilla_de_Espinacas) 573)
       (= (precio-plato Rape_al_Limon) 9)
       (= (cals-plato Rape_al_Limon) 794)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
