(define (problem catering-18platos-0incmpls)
    (:domain catering)
    (:objects Crema_Calabacin Patatas_Caliu Potaje_de_Alubias Macarrones_Bolonesa Ensalada_de_Col Huevos_Rellenos Croquetas Paella Pastel_de_Pan Tagliatelle_Bolonesa Escudella Fideua_con_Sepia Cuscus Ramen Canelones_de_Carne Sushi Judias_Verdes Gazpacho - primero
              Fingers_de_Pollo Canelones_de_Pollo Albondigas Rape_al_Limon Berenjas_al_Horno Sopa_de_Miso Calamares_a_la_Romana Milanesa_Napolitana Raviolli Pastel_de_Verduras Bacalao Suquet_de_Pescado Tortilla_de_Espinacas Costillas_de_Cerdo Salmon_Ahumado Falafel Merluza_a_Naranja Lasana_de_Atun - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Croquetas Carne)
       (es_tipo Paella Pescado)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Escudella Sopa)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Cuscus Vegetal)
       (es_tipo Ramen Sopa)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Sushi Pescado)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Gazpacho Sopa)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Albondigas Carne)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Raviolli Pasta)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Bacalao Pescado)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Falafel Carne)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Lasana_de_Atun Pescado)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Crema_Calabacin) 5)
       (= (cals-plato Crema_Calabacin) 305)
       (= (precio-plato Patatas_Caliu) 6)
       (= (cals-plato Patatas_Caliu) 725)
       (= (precio-plato Potaje_de_Alubias) 9)
       (= (cals-plato Potaje_de_Alubias) 411)
       (= (precio-plato Macarrones_Bolonesa) 7)
       (= (cals-plato Macarrones_Bolonesa) 271)
       (= (precio-plato Ensalada_de_Col) 5)
       (= (cals-plato Ensalada_de_Col) 664)
       (= (precio-plato Huevos_Rellenos) 6)
       (= (cals-plato Huevos_Rellenos) 273)
       (= (precio-plato Croquetas) 5)
       (= (cals-plato Croquetas) 701)
       (= (precio-plato Paella) 7)
       (= (cals-plato Paella) 701)
       (= (precio-plato Pastel_de_Pan) 6)
       (= (cals-plato Pastel_de_Pan) 619)
       (= (precio-plato Tagliatelle_Bolonesa) 8)
       (= (cals-plato Tagliatelle_Bolonesa) 259)
       (= (precio-plato Escudella) 9)
       (= (cals-plato Escudella) 564)
       (= (precio-plato Fideua_con_Sepia) 9)
       (= (cals-plato Fideua_con_Sepia) 503)
       (= (precio-plato Cuscus) 8)
       (= (cals-plato Cuscus) 474)
       (= (precio-plato Ramen) 7)
       (= (cals-plato Ramen) 535)
       (= (precio-plato Canelones_de_Carne) 6)
       (= (cals-plato Canelones_de_Carne) 671)
       (= (precio-plato Sushi) 9)
       (= (cals-plato Sushi) 492)
       (= (precio-plato Judias_Verdes) 6)
       (= (cals-plato Judias_Verdes) 360)
       (= (precio-plato Gazpacho) 6)
       (= (cals-plato Gazpacho) 376)
       (= (precio-plato Fingers_de_Pollo) 14)
       (= (cals-plato Fingers_de_Pollo) 809)
       (= (precio-plato Canelones_de_Pollo) 11)
       (= (cals-plato Canelones_de_Pollo) 513)
       (= (precio-plato Albondigas) 8)
       (= (cals-plato Albondigas) 601)
       (= (precio-plato Rape_al_Limon) 14)
       (= (cals-plato Rape_al_Limon) 861)
       (= (precio-plato Berenjas_al_Horno) 9)
       (= (cals-plato Berenjas_al_Horno) 724)
       (= (precio-plato Sopa_de_Miso) 13)
       (= (cals-plato Sopa_de_Miso) 717)
       (= (precio-plato Calamares_a_la_Romana) 13)
       (= (cals-plato Calamares_a_la_Romana) 664)
       (= (precio-plato Milanesa_Napolitana) 10)
       (= (cals-plato Milanesa_Napolitana) 490)
       (= (precio-plato Raviolli) 13)
       (= (cals-plato Raviolli) 679)
       (= (precio-plato Pastel_de_Verduras) 9)
       (= (cals-plato Pastel_de_Verduras) 598)
       (= (precio-plato Bacalao) 9)
       (= (cals-plato Bacalao) 590)
       (= (precio-plato Suquet_de_Pescado) 14)
       (= (cals-plato Suquet_de_Pescado) 500)
       (= (precio-plato Tortilla_de_Espinacas) 14)
       (= (cals-plato Tortilla_de_Espinacas) 874)
       (= (precio-plato Costillas_de_Cerdo) 14)
       (= (cals-plato Costillas_de_Cerdo) 861)
       (= (precio-plato Salmon_Ahumado) 13)
       (= (cals-plato Salmon_Ahumado) 882)
       (= (precio-plato Falafel) 14)
       (= (cals-plato Falafel) 416)
       (= (precio-plato Merluza_a_Naranja) 14)
       (= (cals-plato Merluza_a_Naranja) 565)
       (= (precio-plato Lasana_de_Atun) 10)
       (= (cals-plato Lasana_de_Atun) 567)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
