(define (problem catering-19platos-5incmpls)
    (:domain catering)
    (:objects Macarrones_Bolonesa Risotto_de_Pescado Escudella Patatas_Caliu Potaje_de_Alubias Ramen Sushi Gazpacho Spaghettis_Bolonesa Cuscus Pastel_de_Pan Huevos_Rellenos Judias_Verdes Crema_Calabacin Canelones_de_Carne Tagliatelle_Bolonesa Paella Fideua_con_Sepia Ensalada_de_Col - primero
              Raviolli Milanesa_Napolitana Pastel_de_Verduras Calamares_a_la_Romana Suquet_de_Pescado Bacalao Rape_al_Limon Falafel Crema_Zanahoria Costillas_de_Cerdo Canelones_de_Pollo Lasana_de_Atun Fingers_de_Pollo Merluza_a_Naranja Albondigas Sopa_de_Miso Tortilla_de_Espinacas Calsotada Berenjas_al_Horno - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Escudella Sopa)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Ramen Sopa)
       (es_tipo Sushi Pescado)
       (es_tipo Gazpacho Sopa)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Cuscus Vegetal)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Paella Pescado)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Raviolli Pasta)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Bacalao Pescado)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Falafel Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Albondigas Carne)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Calsotada Vegetal)
       (es_tipo Berenjas_al_Horno Vegetal)
       (incompatible Huevos_Rellenos Milanesa_Napolitana)
       (incompatible Patatas_Caliu Crema_Zanahoria)
       (incompatible Macarrones_Bolonesa Falafel)
       (incompatible Potaje_de_Alubias Pastel_de_Verduras)
       (incompatible Sushi Fingers_de_Pollo)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Macarrones_Bolonesa) 6)
       (= (cals-plato Macarrones_Bolonesa) 465)
       (= (precio-plato Risotto_de_Pescado) 5)
       (= (cals-plato Risotto_de_Pescado) 258)
       (= (precio-plato Escudella) 5)
       (= (cals-plato Escudella) 599)
       (= (precio-plato Patatas_Caliu) 5)
       (= (cals-plato Patatas_Caliu) 415)
       (= (precio-plato Potaje_de_Alubias) 8)
       (= (cals-plato Potaje_de_Alubias) 254)
       (= (precio-plato Ramen) 6)
       (= (cals-plato Ramen) 509)
       (= (precio-plato Sushi) 6)
       (= (cals-plato Sushi) 359)
       (= (precio-plato Gazpacho) 9)
       (= (cals-plato Gazpacho) 506)
       (= (precio-plato Spaghettis_Bolonesa) 6)
       (= (cals-plato Spaghettis_Bolonesa) 627)
       (= (precio-plato Cuscus) 7)
       (= (cals-plato Cuscus) 669)
       (= (precio-plato Pastel_de_Pan) 6)
       (= (cals-plato Pastel_de_Pan) 309)
       (= (precio-plato Huevos_Rellenos) 9)
       (= (cals-plato Huevos_Rellenos) 741)
       (= (precio-plato Judias_Verdes) 6)
       (= (cals-plato Judias_Verdes) 725)
       (= (precio-plato Crema_Calabacin) 8)
       (= (cals-plato Crema_Calabacin) 382)
       (= (precio-plato Canelones_de_Carne) 5)
       (= (cals-plato Canelones_de_Carne) 665)
       (= (precio-plato Tagliatelle_Bolonesa) 8)
       (= (cals-plato Tagliatelle_Bolonesa) 387)
       (= (precio-plato Paella) 5)
       (= (cals-plato Paella) 590)
       (= (precio-plato Fideua_con_Sepia) 6)
       (= (cals-plato Fideua_con_Sepia) 575)
       (= (precio-plato Ensalada_de_Col) 9)
       (= (cals-plato Ensalada_de_Col) 449)
       (= (precio-plato Raviolli) 12)
       (= (cals-plato Raviolli) 537)
       (= (precio-plato Milanesa_Napolitana) 11)
       (= (cals-plato Milanesa_Napolitana) 729)
       (= (precio-plato Pastel_de_Verduras) 13)
       (= (cals-plato Pastel_de_Verduras) 561)
       (= (precio-plato Calamares_a_la_Romana) 8)
       (= (cals-plato Calamares_a_la_Romana) 605)
       (= (precio-plato Suquet_de_Pescado) 11)
       (= (cals-plato Suquet_de_Pescado) 845)
       (= (precio-plato Bacalao) 14)
       (= (cals-plato Bacalao) 556)
       (= (precio-plato Rape_al_Limon) 10)
       (= (cals-plato Rape_al_Limon) 737)
       (= (precio-plato Falafel) 8)
       (= (cals-plato Falafel) 675)
       (= (precio-plato Crema_Zanahoria) 8)
       (= (cals-plato Crema_Zanahoria) 515)
       (= (precio-plato Costillas_de_Cerdo) 10)
       (= (cals-plato Costillas_de_Cerdo) 440)
       (= (precio-plato Canelones_de_Pollo) 13)
       (= (cals-plato Canelones_de_Pollo) 496)
       (= (precio-plato Lasana_de_Atun) 10)
       (= (cals-plato Lasana_de_Atun) 412)
       (= (precio-plato Fingers_de_Pollo) 13)
       (= (cals-plato Fingers_de_Pollo) 702)
       (= (precio-plato Merluza_a_Naranja) 12)
       (= (cals-plato Merluza_a_Naranja) 828)
       (= (precio-plato Albondigas) 9)
       (= (cals-plato Albondigas) 817)
       (= (precio-plato Sopa_de_Miso) 11)
       (= (cals-plato Sopa_de_Miso) 591)
       (= (precio-plato Tortilla_de_Espinacas) 9)
       (= (cals-plato Tortilla_de_Espinacas) 603)
       (= (precio-plato Calsotada) 11)
       (= (cals-plato Calsotada) 633)
       (= (precio-plato Berenjas_al_Horno) 11)
       (= (cals-plato Berenjas_al_Horno) 608)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
