(define (problem catering-15platos-8incmpls)
    (:domain catering)
    (:objects Ramen Potaje_de_Alubias Macarrones_Bolonesa Gazpacho Sushi Pastel_de_Pan Canelones_de_Carne Huevos_Rellenos Ensalada_de_Col Paella Crema_Calabacin Cuscus Fideua_con_Sepia Patatas_Caliu Judias_Verdes - primero
              Fingers_de_Pollo Falafel Calamares_a_la_Romana Crema_Zanahoria Tortilla_de_Espinacas Suquet_de_Pescado Costillas_de_Cerdo Raviolli Bacalao Rape_al_Limon Pastel_de_Verduras Calsotada Salmon_Ahumado Milanesa_Napolitana Berenjas_al_Horno - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Ramen Sopa)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Gazpacho Sopa)
       (es_tipo Sushi Pescado)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Paella Pescado)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Cuscus Vegetal)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Falafel Carne)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Raviolli Pasta)
       (es_tipo Bacalao Pescado)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Calsotada Vegetal)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Berenjas_al_Horno Vegetal)
       (incompatible Ensalada_de_Col Rape_al_Limon)
       (incompatible Sushi Milanesa_Napolitana)
       (incompatible Fideua_con_Sepia Tortilla_de_Espinacas)
       (incompatible Judias_Verdes Costillas_de_Cerdo)
       (incompatible Patatas_Caliu Pastel_de_Verduras)
       (incompatible Canelones_de_Carne Raviolli)
       (incompatible Gazpacho Falafel)
       (incompatible Pastel_de_Pan Fingers_de_Pollo)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Ramen) 7)
       (= (cals-plato Ramen) 366)
       (= (precio-plato Potaje_de_Alubias) 7)
       (= (cals-plato Potaje_de_Alubias) 433)
       (= (precio-plato Macarrones_Bolonesa) 5)
       (= (cals-plato Macarrones_Bolonesa) 550)
       (= (precio-plato Gazpacho) 8)
       (= (cals-plato Gazpacho) 526)
       (= (precio-plato Sushi) 9)
       (= (cals-plato Sushi) 647)
       (= (precio-plato Pastel_de_Pan) 5)
       (= (cals-plato Pastel_de_Pan) 743)
       (= (precio-plato Canelones_de_Carne) 8)
       (= (cals-plato Canelones_de_Carne) 578)
       (= (precio-plato Huevos_Rellenos) 5)
       (= (cals-plato Huevos_Rellenos) 444)
       (= (precio-plato Ensalada_de_Col) 8)
       (= (cals-plato Ensalada_de_Col) 704)
       (= (precio-plato Paella) 9)
       (= (cals-plato Paella) 459)
       (= (precio-plato Crema_Calabacin) 9)
       (= (cals-plato Crema_Calabacin) 550)
       (= (precio-plato Cuscus) 7)
       (= (cals-plato Cuscus) 366)
       (= (precio-plato Fideua_con_Sepia) 7)
       (= (cals-plato Fideua_con_Sepia) 351)
       (= (precio-plato Patatas_Caliu) 8)
       (= (cals-plato Patatas_Caliu) 570)
       (= (precio-plato Judias_Verdes) 7)
       (= (cals-plato Judias_Verdes) 459)
       (= (precio-plato Fingers_de_Pollo) 10)
       (= (cals-plato Fingers_de_Pollo) 658)
       (= (precio-plato Falafel) 10)
       (= (cals-plato Falafel) 700)
       (= (precio-plato Calamares_a_la_Romana) 14)
       (= (cals-plato Calamares_a_la_Romana) 698)
       (= (precio-plato Crema_Zanahoria) 9)
       (= (cals-plato Crema_Zanahoria) 457)
       (= (precio-plato Tortilla_de_Espinacas) 9)
       (= (cals-plato Tortilla_de_Espinacas) 851)
       (= (precio-plato Suquet_de_Pescado) 12)
       (= (cals-plato Suquet_de_Pescado) 441)
       (= (precio-plato Costillas_de_Cerdo) 12)
       (= (cals-plato Costillas_de_Cerdo) 456)
       (= (precio-plato Raviolli) 12)
       (= (cals-plato Raviolli) 802)
       (= (precio-plato Bacalao) 11)
       (= (cals-plato Bacalao) 536)
       (= (precio-plato Rape_al_Limon) 14)
       (= (cals-plato Rape_al_Limon) 737)
       (= (precio-plato Pastel_de_Verduras) 14)
       (= (cals-plato Pastel_de_Verduras) 408)
       (= (precio-plato Calsotada) 14)
       (= (cals-plato Calsotada) 647)
       (= (precio-plato Salmon_Ahumado) 9)
       (= (cals-plato Salmon_Ahumado) 594)
       (= (precio-plato Milanesa_Napolitana) 13)
       (= (cals-plato Milanesa_Napolitana) 526)
       (= (precio-plato Berenjas_al_Horno) 8)
       (= (cals-plato Berenjas_al_Horno) 561)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
(define (problem catering-15platos-8incmpls)
    (:domain catering)
    (:objects Risotto_de_Pescado Judias_Verdes Escudella Spaghettis_Bolonesa Paella Tagliatelle_Bolonesa Ramen Huevos_Rellenos Patatas_Caliu Fideua_con_Sepia Cuscus Pastel_de_Pan Crema_Calabacin Croquetas Macarrones_Bolonesa - primero
              Raviolli Lasana_de_Atun Albondigas Rape_al_Limon Costillas_de_Cerdo Milanesa_Napolitana Tortilla_de_Espinacas Fingers_de_Pollo Crema_Zanahoria Canelones_de_Pollo Merluza_a_Naranja Sopa_de_Miso Bacalao Salmon_Ahumado Pastel_de_Verduras - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Escudella Sopa)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Paella Pescado)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Ramen Sopa)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Cuscus Vegetal)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Croquetas Carne)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Raviolli Pasta)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Albondigas Carne)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Bacalao Pescado)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Pastel_de_Verduras Vegetal)
       (incompatible Macarrones_Bolonesa Rape_al_Limon)
       (incompatible Risotto_de_Pescado Milanesa_Napolitana)
       (incompatible Paella Costillas_de_Cerdo)
       (incompatible Cuscus Crema_Zanahoria)
       (incompatible Huevos_Rellenos Canelones_de_Pollo)
       (incompatible Tagliatelle_Bolonesa Tortilla_de_Espinacas)
       (incompatible Ramen Sopa_de_Miso)
       (incompatible Spaghettis_Bolonesa Lasana_de_Atun)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Risotto_de_Pescado) 5)
       (= (cals-plato Risotto_de_Pescado) 654)
       (= (precio-plato Judias_Verdes) 6)
       (= (cals-plato Judias_Verdes) 648)
       (= (precio-plato Escudella) 7)
       (= (cals-plato Escudella) 324)
       (= (precio-plato Spaghettis_Bolonesa) 5)
       (= (cals-plato Spaghettis_Bolonesa) 518)
       (= (precio-plato Paella) 5)
       (= (cals-plato Paella) 506)
       (= (precio-plato Tagliatelle_Bolonesa) 5)
       (= (cals-plato Tagliatelle_Bolonesa) 277)
       (= (precio-plato Ramen) 5)
       (= (cals-plato Ramen) 316)
       (= (precio-plato Huevos_Rellenos) 5)
       (= (cals-plato Huevos_Rellenos) 573)
       (= (precio-plato Patatas_Caliu) 8)
       (= (cals-plato Patatas_Caliu) 369)
       (= (precio-plato Fideua_con_Sepia) 6)
       (= (cals-plato Fideua_con_Sepia) 598)
       (= (precio-plato Cuscus) 5)
       (= (cals-plato Cuscus) 732)
       (= (precio-plato Pastel_de_Pan) 8)
       (= (cals-plato Pastel_de_Pan) 266)
       (= (precio-plato Crema_Calabacin) 9)
       (= (cals-plato Crema_Calabacin) 415)
       (= (precio-plato Croquetas) 7)
       (= (cals-plato Croquetas) 502)
       (= (precio-plato Macarrones_Bolonesa) 8)
       (= (cals-plato Macarrones_Bolonesa) 382)
       (= (precio-plato Raviolli) 11)
       (= (cals-plato Raviolli) 618)
       (= (precio-plato Lasana_de_Atun) 11)
       (= (cals-plato Lasana_de_Atun) 511)
       (= (precio-plato Albondigas) 13)
       (= (cals-plato Albondigas) 745)
       (= (precio-plato Rape_al_Limon) 9)
       (= (cals-plato Rape_al_Limon) 556)
       (= (precio-plato Costillas_de_Cerdo) 10)
       (= (cals-plato Costillas_de_Cerdo) 825)
       (= (precio-plato Milanesa_Napolitana) 12)
       (= (cals-plato Milanesa_Napolitana) 666)
       (= (precio-plato Tortilla_de_Espinacas) 10)
       (= (cals-plato Tortilla_de_Espinacas) 682)
       (= (precio-plato Fingers_de_Pollo) 14)
       (= (cals-plato Fingers_de_Pollo) 425)
       (= (precio-plato Crema_Zanahoria) 9)
       (= (cals-plato Crema_Zanahoria) 626)
       (= (precio-plato Canelones_de_Pollo) 10)
       (= (cals-plato Canelones_de_Pollo) 498)
       (= (precio-plato Merluza_a_Naranja) 9)
       (= (cals-plato Merluza_a_Naranja) 742)
       (= (precio-plato Sopa_de_Miso) 9)
       (= (cals-plato Sopa_de_Miso) 841)
       (= (precio-plato Bacalao) 11)
       (= (cals-plato Bacalao) 670)
       (= (precio-plato Salmon_Ahumado) 12)
       (= (cals-plato Salmon_Ahumado) 498)
       (= (precio-plato Pastel_de_Verduras) 10)
       (= (cals-plato Pastel_de_Verduras) 738)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
