(define (problem catering-15platos-3incmpls)
    (:domain catering)
    (:objects Pastel_de_Pan Spaghettis_Bolonesa Risotto_de_Pescado Potaje_de_Alubias Sushi Crema_Calabacin Cuscus Patatas_Caliu Tagliatelle_Bolonesa Croquetas Gazpacho Fideua_con_Sepia Macarrones_Bolonesa Judias_Verdes Canelones_de_Carne - primero
              Pastel_de_Verduras Fingers_de_Pollo Falafel Albondigas Rape_al_Limon Salmon_Ahumado Calsotada Costillas_de_Cerdo Crema_Zanahoria Lasana_de_Atun Sopa_de_Miso Milanesa_Napolitana Bacalao Calamares_a_la_Romana Raviolli - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Lunes Martes Miercoles Jueves Viernes - dia
    )
    (:init
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Sushi Pescado)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Cuscus Vegetal)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Croquetas Carne)
       (es_tipo Gazpacho Sopa)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Falafel Carne)
       (es_tipo Albondigas Carne)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Calsotada Vegetal)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Bacalao Pescado)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Raviolli Pasta)
       (incompatible Fideua_con_Sepia Pastel_de_Verduras)
       (incompatible Potaje_de_Alubias Crema_Zanahoria)
       (incompatible Canelones_de_Carne Rape_al_Limon)
       (plato_dia Jueves Gazpacho)
       (plato_dia Martes Calsotada)
       (plato_dia Lunes Crema_Zanahoria)

       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Pastel_de_Pan) 5)
       (= (cals-plato Pastel_de_Pan) 348)
       (= (precio-plato Spaghettis_Bolonesa) 7)
       (= (cals-plato Spaghettis_Bolonesa) 352)
       (= (precio-plato Risotto_de_Pescado) 7)
       (= (cals-plato Risotto_de_Pescado) 330)
       (= (precio-plato Potaje_de_Alubias) 8)
       (= (cals-plato Potaje_de_Alubias) 413)
       (= (precio-plato Sushi) 6)
       (= (cals-plato Sushi) 725)
       (= (precio-plato Crema_Calabacin) 9)
       (= (cals-plato Crema_Calabacin) 445)
       (= (precio-plato Cuscus) 7)
       (= (cals-plato Cuscus) 582)
       (= (precio-plato Patatas_Caliu) 8)
       (= (cals-plato Patatas_Caliu) 613)
       (= (precio-plato Tagliatelle_Bolonesa) 5)
       (= (cals-plato Tagliatelle_Bolonesa) 393)
       (= (precio-plato Croquetas) 5)
       (= (cals-plato Croquetas) 410)
       (= (precio-plato Gazpacho) 7)
       (= (cals-plato Gazpacho) 693)
       (= (precio-plato Fideua_con_Sepia) 9)
       (= (cals-plato Fideua_con_Sepia) 574)
       (= (precio-plato Macarrones_Bolonesa) 6)
       (= (cals-plato Macarrones_Bolonesa) 580)
       (= (precio-plato Judias_Verdes) 9)
       (= (cals-plato Judias_Verdes) 272)
       (= (precio-plato Canelones_de_Carne) 5)
       (= (cals-plato Canelones_de_Carne) 366)
       (= (precio-plato Pastel_de_Verduras) 13)
       (= (cals-plato Pastel_de_Verduras) 843)
       (= (precio-plato Fingers_de_Pollo) 9)
       (= (cals-plato Fingers_de_Pollo) 601)
       (= (precio-plato Falafel) 10)
       (= (cals-plato Falafel) 450)
       (= (precio-plato Albondigas) 12)
       (= (cals-plato Albondigas) 539)
       (= (precio-plato Rape_al_Limon) 14)
       (= (cals-plato Rape_al_Limon) 473)
       (= (precio-plato Salmon_Ahumado) 10)
       (= (cals-plato Salmon_Ahumado) 804)
       (= (precio-plato Calsotada) 10)
       (= (cals-plato Calsotada) 440)
       (= (precio-plato Costillas_de_Cerdo) 8)
       (= (cals-plato Costillas_de_Cerdo) 451)
       (= (precio-plato Crema_Zanahoria) 14)
       (= (cals-plato Crema_Zanahoria) 817)
       (= (precio-plato Lasana_de_Atun) 9)
       (= (cals-plato Lasana_de_Atun) 826)
       (= (precio-plato Sopa_de_Miso) 12)
       (= (cals-plato Sopa_de_Miso) 419)
       (= (precio-plato Milanesa_Napolitana) 11)
       (= (cals-plato Milanesa_Napolitana) 884)
       (= (precio-plato Bacalao) 13)
       (= (cals-plato Bacalao) 805)
       (= (precio-plato Calamares_a_la_Romana) 8)
       (= (cals-plato Calamares_a_la_Romana) 649)
       (= (precio-plato Raviolli) 14)
       (= (cals-plato Raviolli) 429)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
