(define (problem catering-17platos-6incmpls)
    (:domain catering)
    (:objects Potaje_de_Alubias Patatas_Caliu Tagliatelle_Bolonesa Ramen Sushi Crema_Calabacin Fideua_con_Sepia Pastel_de_Pan Judias_Verdes Paella Ensalada_de_Col Spaghettis_Bolonesa Gazpacho Macarrones_Bolonesa Croquetas Canelones_de_Carne Cuscus - primero
              Rape_al_Limon Calsotada Calamares_a_la_Romana Raviolli Falafel Milanesa_Napolitana Crema_Zanahoria Pastel_de_Verduras Costillas_de_Cerdo Canelones_de_Pollo Albondigas Berenjas_al_Horno Lasana_de_Atun Merluza_a_Naranja Salmon_Ahumado Tortilla_de_Espinacas Fingers_de_Pollo - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Ramen Sopa)
       (es_tipo Sushi Pescado)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Paella Pescado)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Gazpacho Sopa)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Croquetas Carne)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Cuscus Vegetal)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Calsotada Vegetal)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Raviolli Pasta)
       (es_tipo Falafel Carne)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Albondigas Carne)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Fingers_de_Pollo Carne)
       (incompatible Pastel_de_Pan Milanesa_Napolitana)
       (incompatible Ensalada_de_Col Salmon_Ahumado)
       (incompatible Cuscus Merluza_a_Naranja)
       (incompatible Fideua_con_Sepia Rape_al_Limon)
       (incompatible Gazpacho Tortilla_de_Espinacas)
       (incompatible Judias_Verdes Costillas_de_Cerdo)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Potaje_de_Alubias) 9)
       (= (cals-plato Potaje_de_Alubias) 335)
       (= (precio-plato Patatas_Caliu) 7)
       (= (cals-plato Patatas_Caliu) 643)
       (= (precio-plato Tagliatelle_Bolonesa) 5)
       (= (cals-plato Tagliatelle_Bolonesa) 261)
       (= (precio-plato Ramen) 9)
       (= (cals-plato Ramen) 482)
       (= (precio-plato Sushi) 9)
       (= (cals-plato Sushi) 467)
       (= (precio-plato Crema_Calabacin) 6)
       (= (cals-plato Crema_Calabacin) 342)
       (= (precio-plato Fideua_con_Sepia) 8)
       (= (cals-plato Fideua_con_Sepia) 279)
       (= (precio-plato Pastel_de_Pan) 7)
       (= (cals-plato Pastel_de_Pan) 653)
       (= (precio-plato Judias_Verdes) 5)
       (= (cals-plato Judias_Verdes) 622)
       (= (precio-plato Paella) 8)
       (= (cals-plato Paella) 303)
       (= (precio-plato Ensalada_de_Col) 5)
       (= (cals-plato Ensalada_de_Col) 598)
       (= (precio-plato Spaghettis_Bolonesa) 7)
       (= (cals-plato Spaghettis_Bolonesa) 371)
       (= (precio-plato Gazpacho) 5)
       (= (cals-plato Gazpacho) 570)
       (= (precio-plato Macarrones_Bolonesa) 8)
       (= (cals-plato Macarrones_Bolonesa) 539)
       (= (precio-plato Croquetas) 6)
       (= (cals-plato Croquetas) 508)
       (= (precio-plato Canelones_de_Carne) 9)
       (= (cals-plato Canelones_de_Carne) 521)
       (= (precio-plato Cuscus) 8)
       (= (cals-plato Cuscus) 582)
       (= (precio-plato Rape_al_Limon) 10)
       (= (cals-plato Rape_al_Limon) 469)
       (= (precio-plato Calsotada) 11)
       (= (cals-plato Calsotada) 594)
       (= (precio-plato Calamares_a_la_Romana) 9)
       (= (cals-plato Calamares_a_la_Romana) 412)
       (= (precio-plato Raviolli) 9)
       (= (cals-plato Raviolli) 445)
       (= (precio-plato Falafel) 10)
       (= (cals-plato Falafel) 852)
       (= (precio-plato Milanesa_Napolitana) 13)
       (= (cals-plato Milanesa_Napolitana) 558)
       (= (precio-plato Crema_Zanahoria) 11)
       (= (cals-plato Crema_Zanahoria) 697)
       (= (precio-plato Pastel_de_Verduras) 8)
       (= (cals-plato Pastel_de_Verduras) 824)
       (= (precio-plato Costillas_de_Cerdo) 13)
       (= (cals-plato Costillas_de_Cerdo) 778)
       (= (precio-plato Canelones_de_Pollo) 8)
       (= (cals-plato Canelones_de_Pollo) 417)
       (= (precio-plato Albondigas) 14)
       (= (cals-plato Albondigas) 565)
       (= (precio-plato Berenjas_al_Horno) 12)
       (= (cals-plato Berenjas_al_Horno) 596)
       (= (precio-plato Lasana_de_Atun) 8)
       (= (cals-plato Lasana_de_Atun) 434)
       (= (precio-plato Merluza_a_Naranja) 10)
       (= (cals-plato Merluza_a_Naranja) 437)
       (= (precio-plato Salmon_Ahumado) 14)
       (= (cals-plato Salmon_Ahumado) 579)
       (= (precio-plato Tortilla_de_Espinacas) 8)
       (= (cals-plato Tortilla_de_Espinacas) 432)
       (= (precio-plato Fingers_de_Pollo) 9)
       (= (cals-plato Fingers_de_Pollo) 537)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
