(define (problem catering-19platos-9incmpls)
    (:domain catering)
    (:objects Cuscus Pastel_de_Pan Ensalada_de_Col Huevos_Rellenos Gazpacho Paella Crema_Calabacin Spaghettis_Bolonesa Ramen Escudella Judias_Verdes Macarrones_Bolonesa Sushi Risotto_de_Pescado Potaje_de_Alubias Tagliatelle_Bolonesa Canelones_de_Carne Croquetas Fideua_con_Sepia - primero
              Albondigas Calamares_a_la_Romana Crema_Zanahoria Calsotada Berenjas_al_Horno Lasana_de_Atun Canelones_de_Pollo Raviolli Rape_al_Limon Fingers_de_Pollo Sopa_de_Miso Suquet_de_Pescado Costillas_de_Cerdo Pastel_de_Verduras Falafel Merluza_a_Naranja Tortilla_de_Espinacas Salmon_Ahumado Milanesa_Napolitana - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Cuscus Vegetal)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Gazpacho Sopa)
       (es_tipo Paella Pescado)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Ramen Sopa)
       (es_tipo Escudella Sopa)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Sushi Pescado)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Croquetas Carne)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Albondigas Carne)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Calsotada Vegetal)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Raviolli Pasta)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Falafel Carne)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Milanesa_Napolitana Carne)
       (incompatible Crema_Calabacin Milanesa_Napolitana)
       (incompatible Cuscus Salmon_Ahumado)
       (incompatible Judias_Verdes Fingers_de_Pollo)
       (incompatible Tagliatelle_Bolonesa Sopa_de_Miso)
       (incompatible Gazpacho Calamares_a_la_Romana)
       (incompatible Escudella Suquet_de_Pescado)
       (incompatible Spaghettis_Bolonesa Lasana_de_Atun)
       (incompatible Risotto_de_Pescado Albondigas)
       (incompatible Ramen Crema_Zanahoria)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Cuscus) 8)
       (= (cals-plato Cuscus) 642)
       (= (precio-plato Pastel_de_Pan) 8)
       (= (cals-plato Pastel_de_Pan) 283)
       (= (precio-plato Ensalada_de_Col) 8)
       (= (cals-plato Ensalada_de_Col) 313)
       (= (precio-plato Huevos_Rellenos) 7)
       (= (cals-plato Huevos_Rellenos) 330)
       (= (precio-plato Gazpacho) 9)
       (= (cals-plato Gazpacho) 434)
       (= (precio-plato Paella) 7)
       (= (cals-plato Paella) 481)
       (= (precio-plato Crema_Calabacin) 9)
       (= (cals-plato Crema_Calabacin) 298)
       (= (precio-plato Spaghettis_Bolonesa) 5)
       (= (cals-plato Spaghettis_Bolonesa) 454)
       (= (precio-plato Ramen) 6)
       (= (cals-plato Ramen) 744)
       (= (precio-plato Escudella) 7)
       (= (cals-plato Escudella) 504)
       (= (precio-plato Judias_Verdes) 8)
       (= (cals-plato Judias_Verdes) 260)
       (= (precio-plato Macarrones_Bolonesa) 8)
       (= (cals-plato Macarrones_Bolonesa) 465)
       (= (precio-plato Sushi) 5)
       (= (cals-plato Sushi) 560)
       (= (precio-plato Risotto_de_Pescado) 6)
       (= (cals-plato Risotto_de_Pescado) 585)
       (= (precio-plato Potaje_de_Alubias) 7)
       (= (cals-plato Potaje_de_Alubias) 725)
       (= (precio-plato Tagliatelle_Bolonesa) 5)
       (= (cals-plato Tagliatelle_Bolonesa) 294)
       (= (precio-plato Canelones_de_Carne) 9)
       (= (cals-plato Canelones_de_Carne) 419)
       (= (precio-plato Croquetas) 6)
       (= (cals-plato Croquetas) 609)
       (= (precio-plato Fideua_con_Sepia) 7)
       (= (cals-plato Fideua_con_Sepia) 314)
       (= (precio-plato Albondigas) 12)
       (= (cals-plato Albondigas) 755)
       (= (precio-plato Calamares_a_la_Romana) 8)
       (= (cals-plato Calamares_a_la_Romana) 781)
       (= (precio-plato Crema_Zanahoria) 9)
       (= (cals-plato Crema_Zanahoria) 553)
       (= (precio-plato Calsotada) 10)
       (= (cals-plato Calsotada) 600)
       (= (precio-plato Berenjas_al_Horno) 10)
       (= (cals-plato Berenjas_al_Horno) 649)
       (= (precio-plato Lasana_de_Atun) 11)
       (= (cals-plato Lasana_de_Atun) 866)
       (= (precio-plato Canelones_de_Pollo) 8)
       (= (cals-plato Canelones_de_Pollo) 856)
       (= (precio-plato Raviolli) 11)
       (= (cals-plato Raviolli) 748)
       (= (precio-plato Rape_al_Limon) 8)
       (= (cals-plato Rape_al_Limon) 469)
       (= (precio-plato Fingers_de_Pollo) 8)
       (= (cals-plato Fingers_de_Pollo) 426)
       (= (precio-plato Sopa_de_Miso) 12)
       (= (cals-plato Sopa_de_Miso) 732)
       (= (precio-plato Suquet_de_Pescado) 8)
       (= (cals-plato Suquet_de_Pescado) 798)
       (= (precio-plato Costillas_de_Cerdo) 14)
       (= (cals-plato Costillas_de_Cerdo) 851)
       (= (precio-plato Pastel_de_Verduras) 14)
       (= (cals-plato Pastel_de_Verduras) 466)
       (= (precio-plato Falafel) 11)
       (= (cals-plato Falafel) 638)
       (= (precio-plato Merluza_a_Naranja) 11)
       (= (cals-plato Merluza_a_Naranja) 475)
       (= (precio-plato Tortilla_de_Espinacas) 14)
       (= (cals-plato Tortilla_de_Espinacas) 855)
       (= (precio-plato Salmon_Ahumado) 14)
       (= (cals-plato Salmon_Ahumado) 472)
       (= (precio-plato Milanesa_Napolitana) 11)
       (= (cals-plato Milanesa_Napolitana) 612)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)