(define (problem catering-16platos-1incmpls)
    (:domain catering)
    (:objects Escudella Risotto_de_Pescado Pastel_de_Pan Croquetas Huevos_Rellenos Fideua_con_Sepia Gazpacho Potaje_de_Alubias Tagliatelle_Bolonesa Paella Judias_Verdes Sushi Cuscus Patatas_Caliu Ramen Canelones_de_Carne - primero
              Crema_Zanahoria Pastel_de_Verduras Berenjas_al_Horno Raviolli Albondigas Lasana_de_Atun Sopa_de_Miso Milanesa_Napolitana Salmon_Ahumado Costillas_de_Cerdo Canelones_de_Pollo Falafel Calsotada Suquet_de_Pescado Bacalao Fingers_de_Pollo - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Lunes Martes Miercoles Jueves Viernes - dia
    )
    (:init
       (es_tipo Escudella Sopa)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Croquetas Carne)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Gazpacho Sopa)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Paella Pescado)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Sushi Pescado)
       (es_tipo Cuscus Vegetal)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Ramen Sopa)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Raviolli Pasta)
       (es_tipo Albondigas Carne)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Falafel Carne)
       (es_tipo Calsotada Vegetal)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Bacalao Pescado)
       (es_tipo Fingers_de_Pollo Carne)
       (incompatible Risotto_de_Pescado Fingers_de_Pollo)
       (not (servido Lunes))
       (not (servido Martes))
       (not (servido Miercoles))
       (not (servido Jueves))
       (not (servido Viernes))
       (plato_dia Viernes Fingers_de_Pollo)
       (plato_dia Miercoles Huevos_Rellenos)
       (= (precio-plato Escudella) 6)
       (= (cals-plato Escudella) 702)
       (= (precio-plato Risotto_de_Pescado) 9)
       (= (cals-plato Risotto_de_Pescado) 529)
       (= (precio-plato Pastel_de_Pan) 6)
       (= (cals-plato Pastel_de_Pan) 590)
       (= (precio-plato Croquetas) 9)
       (= (cals-plato Croquetas) 700)
       (= (precio-plato Huevos_Rellenos) 7)
       (= (cals-plato Huevos_Rellenos) 646)
       (= (precio-plato Fideua_con_Sepia) 9)
       (= (cals-plato Fideua_con_Sepia) 521)
       (= (precio-plato Gazpacho) 7)
       (= (cals-plato Gazpacho) 261)
       (= (precio-plato Potaje_de_Alubias) 6)
       (= (cals-plato Potaje_de_Alubias) 698)
       (= (precio-plato Tagliatelle_Bolonesa) 7)
       (= (cals-plato Tagliatelle_Bolonesa) 265)
       (= (precio-plato Paella) 6)
       (= (cals-plato Paella) 698)
       (= (precio-plato Judias_Verdes) 9)
       (= (cals-plato Judias_Verdes) 271)
       (= (precio-plato Sushi) 5)
       (= (cals-plato Sushi) 616)
       (= (precio-plato Cuscus) 7)
       (= (cals-plato Cuscus) 737)
       (= (precio-plato Patatas_Caliu) 5)
       (= (cals-plato Patatas_Caliu) 257)
       (= (precio-plato Ramen) 6)
       (= (cals-plato Ramen) 369)
       (= (precio-plato Canelones_de_Carne) 5)
       (= (cals-plato Canelones_de_Carne) 637)
       (= (precio-plato Crema_Zanahoria) 8)
       (= (cals-plato Crema_Zanahoria) 405)
       (= (precio-plato Pastel_de_Verduras) 13)
       (= (cals-plato Pastel_de_Verduras) 745)
       (= (precio-plato Berenjas_al_Horno) 9)
       (= (cals-plato Berenjas_al_Horno) 512)
       (= (precio-plato Raviolli) 10)
       (= (cals-plato Raviolli) 712)
       (= (precio-plato Albondigas) 10)
       (= (cals-plato Albondigas) 585)
       (= (precio-plato Lasana_de_Atun) 12)
       (= (cals-plato Lasana_de_Atun) 717)
       (= (precio-plato Sopa_de_Miso) 12)
       (= (cals-plato Sopa_de_Miso) 814)
       (= (precio-plato Milanesa_Napolitana) 11)
       (= (cals-plato Milanesa_Napolitana) 554)
       (= (precio-plato Salmon_Ahumado) 14)
       (= (cals-plato Salmon_Ahumado) 552)
       (= (precio-plato Costillas_de_Cerdo) 10)
       (= (cals-plato Costillas_de_Cerdo) 745)
       (= (precio-plato Canelones_de_Pollo) 10)
       (= (cals-plato Canelones_de_Pollo) 581)
       (= (precio-plato Falafel) 10)
       (= (cals-plato Falafel) 898)
       (= (precio-plato Calsotada) 8)
       (= (cals-plato Calsotada) 590)
       (= (precio-plato Suquet_de_Pescado) 9)
       (= (cals-plato Suquet_de_Pescado) 899)
       (= (precio-plato Bacalao) 8)
       (= (cals-plato Bacalao) 420)
       (= (precio-plato Fingers_de_Pollo) 11)
       (= (cals-plato Fingers_de_Pollo) 433)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
