(define (problem catering-15platos-7incmpls)
    (:domain catering)
    (:objects Tagliatelle_Bolonesa Potaje_de_Alubias Pastel_de_Pan Sushi Fideua_con_Sepia Ramen Escudella Ensalada_de_Col Cuscus Huevos_Rellenos Spaghettis_Bolonesa Macarrones_Bolonesa Patatas_Caliu Judias_Verdes Canelones_de_Carne - primero
              Milanesa_Napolitana Bacalao Sopa_de_Miso Pastel_de_Verduras Albondigas Crema_Zanahoria Fingers_de_Pollo Suquet_de_Pescado Tortilla_de_Espinacas Rape_al_Limon Berenjas_al_Horno Salmon_Ahumado Lasana_de_Atun Canelones_de_Pollo Raviolli - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Lunes Martes Miercoles Jueves Viernes - dia
    )
    (:init
       (es_tipo Tagliatelle_Bolonesa Pasta)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Sushi Pescado)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Ramen Sopa)
       (es_tipo Escudella Sopa)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Cuscus Vegetal)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Bacalao Pescado)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Pastel_de_Verduras Vegetal)
       (es_tipo Albondigas Carne)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Raviolli Pasta)
       (incompatible Escudella Suquet_de_Pescado)
       (incompatible Spaghettis_Bolonesa Sopa_de_Miso)
       (incompatible Potaje_de_Alubias Rape_al_Limon)
       (incompatible Tagliatelle_Bolonesa Crema_Zanahoria)
       (incompatible Sushi Raviolli)
       (incompatible Macarrones_Bolonesa Tortilla_de_Espinacas)
       (incompatible Huevos_Rellenos Fingers_de_Pollo)
       (not (servido Lunes))
       (not (servido Martes))
       (not (servido Miercoles))
       (not (servido Jueves))
       (not (servido Viernes))
       (plato_dia Viernes Albondigas)
       (plato_dia Lunes Crema_Zanahoria)
       (= (precio-plato Tagliatelle_Bolonesa) 8)
       (= (cals-plato Tagliatelle_Bolonesa) 446)
       (= (precio-plato Potaje_de_Alubias) 7)
       (= (cals-plato Potaje_de_Alubias) 537)
       (= (precio-plato Pastel_de_Pan) 7)
       (= (cals-plato Pastel_de_Pan) 740)
       (= (precio-plato Sushi) 6)
       (= (cals-plato Sushi) 402)
       (= (precio-plato Fideua_con_Sepia) 8)
       (= (cals-plato Fideua_con_Sepia) 429)
       (= (precio-plato Ramen) 9)
       (= (cals-plato Ramen) 550)
       (= (precio-plato Escudella) 8)
       (= (cals-plato Escudella) 410)
       (= (precio-plato Ensalada_de_Col) 9)
       (= (cals-plato Ensalada_de_Col) 714)
       (= (precio-plato Cuscus) 6)
       (= (cals-plato Cuscus) 443)
       (= (precio-plato Huevos_Rellenos) 5)
       (= (cals-plato Huevos_Rellenos) 744)
       (= (precio-plato Spaghettis_Bolonesa) 5)
       (= (cals-plato Spaghettis_Bolonesa) 701)
       (= (precio-plato Macarrones_Bolonesa) 9)
       (= (cals-plato Macarrones_Bolonesa) 723)
       (= (precio-plato Patatas_Caliu) 7)
       (= (cals-plato Patatas_Caliu) 634)
       (= (precio-plato Judias_Verdes) 5)
       (= (cals-plato Judias_Verdes) 375)
       (= (precio-plato Canelones_de_Carne) 8)
       (= (cals-plato Canelones_de_Carne) 466)
       (= (precio-plato Milanesa_Napolitana) 11)
       (= (cals-plato Milanesa_Napolitana) 776)
       (= (precio-plato Bacalao) 11)
       (= (cals-plato Bacalao) 833)
       (= (precio-plato Sopa_de_Miso) 12)
       (= (cals-plato Sopa_de_Miso) 781)
       (= (precio-plato Pastel_de_Verduras) 10)
       (= (cals-plato Pastel_de_Verduras) 892)
       (= (precio-plato Albondigas) 11)
       (= (cals-plato Albondigas) 707)
       (= (precio-plato Crema_Zanahoria) 10)
       (= (cals-plato Crema_Zanahoria) 613)
       (= (precio-plato Fingers_de_Pollo) 14)
       (= (cals-plato Fingers_de_Pollo) 700)
       (= (precio-plato Suquet_de_Pescado) 9)
       (= (cals-plato Suquet_de_Pescado) 869)
       (= (precio-plato Tortilla_de_Espinacas) 11)
       (= (cals-plato Tortilla_de_Espinacas) 693)
       (= (precio-plato Rape_al_Limon) 11)
       (= (cals-plato Rape_al_Limon) 552)
       (= (precio-plato Berenjas_al_Horno) 13)
       (= (cals-plato Berenjas_al_Horno) 697)
       (= (precio-plato Salmon_Ahumado) 10)
       (= (cals-plato Salmon_Ahumado) 660)
       (= (precio-plato Lasana_de_Atun) 10)
       (= (cals-plato Lasana_de_Atun) 575)
       (= (precio-plato Canelones_de_Pollo) 13)
       (= (cals-plato Canelones_de_Pollo) 889)
       (= (precio-plato Raviolli) 8)
       (= (cals-plato Raviolli) 739)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
