(define (problem catering-18platos-8incmpls)
    (:domain catering)
    (:objects Gazpacho Pastel_de_Pan Fideua_con_Sepia Cuscus Crema_Calabacin Patatas_Caliu Judias_Verdes Spaghettis_Bolonesa Escudella Paella Sushi Huevos_Rellenos Risotto_de_Pescado Ramen Croquetas Ensalada_de_Col Canelones_de_Carne Potaje_de_Alubias - primero
              Raviolli Calamares_a_la_Romana Sopa_de_Miso Lasana_de_Atun Tortilla_de_Espinacas Bacalao Crema_Zanahoria Canelones_de_Pollo Merluza_a_Naranja Suquet_de_Pescado Fingers_de_Pollo Calsotada Berenjas_al_Horno Salmon_Ahumado Albondigas Rape_al_Limon Falafel Pastel_de_Verduras - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Lunes Martes Miercoles Jueves Viernes - dia
    )
    (:init
       (es_tipo Gazpacho Sopa)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Fideua_con_Sepia Pescado)
       (es_tipo Cuscus Vegetal)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Patatas_Caliu Vegetal)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Spaghettis_Bolonesa Pasta)
       (es_tipo Escudella Sopa)
       (es_tipo Paella Pescado)
       (es_tipo Sushi Pescado)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Ramen Sopa)
       (es_tipo Croquetas Carne)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Raviolli Pasta)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Bacalao Pescado)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Merluza_a_Naranja Pescado)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Calsotada Vegetal)
       (es_tipo Berenjas_al_Horno Vegetal)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Albondigas Carne)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Falafel Carne)
       (es_tipo Pastel_de_Verduras Vegetal)
       (incompatible Judias_Verdes Berenjas_al_Horno)
       (incompatible Fideua_con_Sepia Bacalao)
       (incompatible Croquetas Tortilla_de_Espinacas)
       (incompatible Gazpacho Falafel)
       (incompatible Spaghettis_Bolonesa Lasana_de_Atun)
       (incompatible Pastel_de_Pan Calsotada)
       (incompatible Sushi Suquet_de_Pescado)
       (incompatible Patatas_Caliu Salmon_Ahumado)
       (not (servido Lunes))
       (not (servido Martes))
       (not (servido Miercoles))
       (not (servido Jueves))
       (not (servido Viernes))
       (plato_dia Miercoles Calsotada)
       (= (precio-plato Gazpacho) 7)
       (= (cals-plato Gazpacho) 448)
       (= (precio-plato Pastel_de_Pan) 9)
       (= (cals-plato Pastel_de_Pan) 563)
       (= (precio-plato Fideua_con_Sepia) 8)
       (= (cals-plato Fideua_con_Sepia) 272)
       (= (precio-plato Cuscus) 6)
       (= (cals-plato Cuscus) 527)
       (= (precio-plato Crema_Calabacin) 8)
       (= (cals-plato Crema_Calabacin) 271)
       (= (precio-plato Patatas_Caliu) 9)
       (= (cals-plato Patatas_Caliu) 745)
       (= (precio-plato Judias_Verdes) 5)
       (= (cals-plato Judias_Verdes) 344)
       (= (precio-plato Spaghettis_Bolonesa) 5)
       (= (cals-plato Spaghettis_Bolonesa) 710)
       (= (precio-plato Escudella) 7)
       (= (cals-plato Escudella) 259)
       (= (precio-plato Paella) 8)
       (= (cals-plato Paella) 539)
       (= (precio-plato Sushi) 6)
       (= (cals-plato Sushi) 477)
       (= (precio-plato Huevos_Rellenos) 6)
       (= (cals-plato Huevos_Rellenos) 308)
       (= (precio-plato Risotto_de_Pescado) 8)
       (= (cals-plato Risotto_de_Pescado) 580)
       (= (precio-plato Ramen) 7)
       (= (cals-plato Ramen) 544)
       (= (precio-plato Croquetas) 6)
       (= (cals-plato Croquetas) 303)
       (= (precio-plato Ensalada_de_Col) 9)
       (= (cals-plato Ensalada_de_Col) 497)
       (= (precio-plato Canelones_de_Carne) 6)
       (= (cals-plato Canelones_de_Carne) 308)
       (= (precio-plato Potaje_de_Alubias) 5)
       (= (cals-plato Potaje_de_Alubias) 576)
       (= (precio-plato Raviolli) 9)
       (= (cals-plato Raviolli) 432)
       (= (precio-plato Calamares_a_la_Romana) 9)
       (= (cals-plato Calamares_a_la_Romana) 831)
       (= (precio-plato Sopa_de_Miso) 13)
       (= (cals-plato Sopa_de_Miso) 703)
       (= (precio-plato Lasana_de_Atun) 13)
       (= (cals-plato Lasana_de_Atun) 519)
       (= (precio-plato Tortilla_de_Espinacas) 14)
       (= (cals-plato Tortilla_de_Espinacas) 546)
       (= (precio-plato Bacalao) 8)
       (= (cals-plato Bacalao) 612)
       (= (precio-plato Crema_Zanahoria) 8)
       (= (cals-plato Crema_Zanahoria) 856)
       (= (precio-plato Canelones_de_Pollo) 11)
       (= (cals-plato Canelones_de_Pollo) 828)
       (= (precio-plato Merluza_a_Naranja) 12)
       (= (cals-plato Merluza_a_Naranja) 853)
       (= (precio-plato Suquet_de_Pescado) 12)
       (= (cals-plato Suquet_de_Pescado) 557)
       (= (precio-plato Fingers_de_Pollo) 13)
       (= (cals-plato Fingers_de_Pollo) 797)
       (= (precio-plato Calsotada) 9)
       (= (cals-plato Calsotada) 522)
       (= (precio-plato Berenjas_al_Horno) 8)
       (= (cals-plato Berenjas_al_Horno) 710)
       (= (precio-plato Salmon_Ahumado) 8)
       (= (cals-plato Salmon_Ahumado) 700)
       (= (precio-plato Albondigas) 8)
       (= (cals-plato Albondigas) 855)
       (= (precio-plato Rape_al_Limon) 14)
       (= (cals-plato Rape_al_Limon) 519)
       (= (precio-plato Falafel) 9)
       (= (cals-plato Falafel) 727)
       (= (precio-plato Pastel_de_Verduras) 10)
       (= (cals-plato Pastel_de_Verduras) 816)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
