(define (problem catering-16platos-9incmpls)
    (:domain catering)
    (:objects Cuscus Canelones_de_Carne Potaje_de_Alubias Croquetas Gazpacho Judias_Verdes Risotto_de_Pescado Paella Sushi Ensalada_de_Col Escudella Ramen Huevos_Rellenos Macarrones_Bolonesa Pastel_de_Pan Crema_Calabacin - primero
              Canelones_de_Pollo Raviolli Costillas_de_Cerdo Calamares_a_la_Romana Milanesa_Napolitana Tortilla_de_Espinacas Fingers_de_Pollo Suquet_de_Pescado Crema_Zanahoria Lasana_de_Atun Rape_al_Limon Salmon_Ahumado Albondigas Calsotada Sopa_de_Miso Merluza_a_Naranja - segundo
              Pescado Carne Pasta Vegetal Sopa - tipo
              Viernes Jueves Miercoles Martes Lunes - dia
    )
    (:init
       (es_tipo Cuscus Vegetal)
       (es_tipo Canelones_de_Carne Carne)
       (es_tipo Potaje_de_Alubias Sopa)
       (es_tipo Croquetas Carne)
       (es_tipo Gazpacho Sopa)
       (es_tipo Judias_Verdes Vegetal)
       (es_tipo Risotto_de_Pescado Pescado)
       (es_tipo Paella Pescado)
       (es_tipo Sushi Pescado)
       (es_tipo Ensalada_de_Col Vegetal)
       (es_tipo Escudella Sopa)
       (es_tipo Ramen Sopa)
       (es_tipo Huevos_Rellenos Carne)
       (es_tipo Macarrones_Bolonesa Pasta)
       (es_tipo Pastel_de_Pan Vegetal)
       (es_tipo Crema_Calabacin Vegetal)
       (es_tipo Canelones_de_Pollo Carne)
       (es_tipo Raviolli Pasta)
       (es_tipo Costillas_de_Cerdo Carne)
       (es_tipo Calamares_a_la_Romana Pescado)
       (es_tipo Milanesa_Napolitana Carne)
       (es_tipo Tortilla_de_Espinacas Vegetal)
       (es_tipo Fingers_de_Pollo Carne)
       (es_tipo Suquet_de_Pescado Sopa)
       (es_tipo Crema_Zanahoria Sopa)
       (es_tipo Lasana_de_Atun Pescado)
       (es_tipo Rape_al_Limon Pescado)
       (es_tipo Salmon_Ahumado Pescado)
       (es_tipo Albondigas Carne)
       (es_tipo Calsotada Vegetal)
       (es_tipo Sopa_de_Miso Sopa)
       (es_tipo Merluza_a_Naranja Pescado)
       (incompatible Gazpacho Rape_al_Limon)
       (incompatible Escudella Calsotada)
       (incompatible Ramen Costillas_de_Cerdo)
       (incompatible Ensalada_de_Col Calamares_a_la_Romana)
       (incompatible Risotto_de_Pescado Fingers_de_Pollo)
       (incompatible Canelones_de_Carne Salmon_Ahumado)
       (incompatible Judias_Verdes Sopa_de_Miso)
       (incompatible Cuscus Raviolli)
       (incompatible Huevos_Rellenos Milanesa_Napolitana)
       (plato_dia Jueves Paella)
       (not (servido Viernes))
       (not (servido Jueves))
       (not (servido Miercoles))
       (not (servido Martes))
       (not (servido Lunes))
       (= (precio-plato Cuscus) 6)
       (= (cals-plato Cuscus) 350)
       (= (precio-plato Canelones_de_Carne) 9)
       (= (cals-plato Canelones_de_Carne) 460)
       (= (precio-plato Potaje_de_Alubias) 9)
       (= (cals-plato Potaje_de_Alubias) 710)
       (= (precio-plato Croquetas) 5)
       (= (cals-plato Croquetas) 491)
       (= (precio-plato Gazpacho) 8)
       (= (cals-plato Gazpacho) 354)
       (= (precio-plato Judias_Verdes) 9)
       (= (cals-plato Judias_Verdes) 366)
       (= (precio-plato Risotto_de_Pescado) 7)
       (= (cals-plato Risotto_de_Pescado) 648)
       (= (precio-plato Paella) 5)
       (= (cals-plato Paella) 253)
       (= (precio-plato Sushi) 7)
       (= (cals-plato Sushi) 488)
       (= (precio-plato Ensalada_de_Col) 8)
       (= (cals-plato Ensalada_de_Col) 558)
       (= (precio-plato Escudella) 8)
       (= (cals-plato Escudella) 613)
       (= (precio-plato Ramen) 9)
       (= (cals-plato Ramen) 578)
       (= (precio-plato Huevos_Rellenos) 8)
       (= (cals-plato Huevos_Rellenos) 251)
       (= (precio-plato Macarrones_Bolonesa) 5)
       (= (cals-plato Macarrones_Bolonesa) 363)
       (= (precio-plato Pastel_de_Pan) 9)
       (= (cals-plato Pastel_de_Pan) 350)
       (= (precio-plato Crema_Calabacin) 9)
       (= (cals-plato Crema_Calabacin) 576)
       (= (precio-plato Canelones_de_Pollo) 12)
       (= (cals-plato Canelones_de_Pollo) 830)
       (= (precio-plato Raviolli) 10)
       (= (cals-plato Raviolli) 527)
       (= (precio-plato Costillas_de_Cerdo) 8)
       (= (cals-plato Costillas_de_Cerdo) 797)
       (= (precio-plato Calamares_a_la_Romana) 12)
       (= (cals-plato Calamares_a_la_Romana) 670)
       (= (precio-plato Milanesa_Napolitana) 10)
       (= (cals-plato Milanesa_Napolitana) 720)
       (= (precio-plato Tortilla_de_Espinacas) 12)
       (= (cals-plato Tortilla_de_Espinacas) 405)
       (= (precio-plato Fingers_de_Pollo) 12)
       (= (cals-plato Fingers_de_Pollo) 895)
       (= (precio-plato Suquet_de_Pescado) 13)
       (= (cals-plato Suquet_de_Pescado) 778)
       (= (precio-plato Crema_Zanahoria) 14)
       (= (cals-plato Crema_Zanahoria) 505)
       (= (precio-plato Lasana_de_Atun) 10)
       (= (cals-plato Lasana_de_Atun) 617)
       (= (precio-plato Rape_al_Limon) 10)
       (= (cals-plato Rape_al_Limon) 428)
       (= (precio-plato Salmon_Ahumado) 11)
       (= (cals-plato Salmon_Ahumado) 734)
       (= (precio-plato Albondigas) 14)
       (= (cals-plato Albondigas) 663)
       (= (precio-plato Calsotada) 13)
       (= (cals-plato Calsotada) 432)
       (= (precio-plato Sopa_de_Miso) 12)
       (= (cals-plato Sopa_de_Miso) 481)
       (= (precio-plato Merluza_a_Naranja) 13)
       (= (cals-plato Merluza_a_Naranja) 783)
       (= (total-cost) 0)
    )
    (:goal (
         forall (?d - dia) (servido ?d)
        )
    )
    (:metric minimize (total-cost))
)
